import Counter from './Couter';

function HowItWorks() {

    return (
        <section class="section-how" id="how">
            {/* <Counter/> */}
            <div class="container">
                <span class="subheading">How it works</span>
                <h2 class="heading-secondary">
                    Your Ultimate Game Plan in 3 Easy Steps
                </h2>
            </div>

            <div class="container grid grid--2-cols-for-home grid--center-v">

                <div class="step-text-box">
                    <p class="step-number">01</p>
                    <h3 class="heading-tertiary">
                        Define Your Game Plan
                    </h3>
                    <p class="step-description">
                        No more guessing games about what gear suits your game best. Share your preferences, and our SportsGear AI will curate a personalized selection tailored to your sport and style, ensuring you have everything you need to dominate the field.
                    </p>
                </div>

                <div class="step-img-box">
                    <img
                        src="./app-screen-1.png"
                        class="step-img"
                        alt="iPhone app
            preferences selection screen"
                    />
                </div>


                <div class="step-img-box">
                    <img
                        src="./app-screen-2.png"
                        class="step-img"
                        alt="iPhone app
            meal approving plan screen"
                    />
                </div>
                <div class="step-text-box">
                    <p class="step-number">02</p>
                    <h3 class="heading-tertiary">Review Your Lineup</h3>
                    <p class="step-description">
                        Once a week, review your tailored selection generated by SportsGear AI. You have the flexibility to tweak your choices, switch out items, or even add your own must-have equipment.
                    </p>
                </div>


                <div class="step-text-box">
                    <p class="step-number">03</p>
                    <h3 class="heading-tertiary">Score with Seamless Delivery</h3>
                    <p class="step-description">
                        Top-notch brands will gear up your game, and we'll deliver your selections straight to your doorstep, fitting into your schedule like a well-timed substitution. Modify your delivery preferences or address whenever necessary for the ultimate convenience!
                    </p>
                </div>
                <div class="step-img-box">
                    <img
                        src="./app-screen-3.png"
                        class="step-img"
                        alt="iPhone app
            delivery screen"
                    />
                </div>
            </div>
        </section>

    );

}
export default HowItWorks;